alpha_fixed_emb: 0.95
asso_func: giou
aw_off: false
aw_param: 0.5
cmc_off: false
conf: 0.424880788280455
delta_t: 1
det_thresh: 0
embedding_off: false
inertia: 0.3348497441538068
iou_thresh: 0.2625783256595632
max_age: 50
min_hits: 1
new_kf_off: false
w_association_emb: 0.75
